name: Belix File System

on: 
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Vlang
        shell: bash
        run: |
          sudo apt install build-essential
          sudo apt install make gcc g++ -y
          sudo mkdir -p /opt/v
          git clone https://github.com/vlang/v.git /opt/v/
          sudo make -C /opt/v/ all
          /opt/v/v
          
